trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_l_gpu
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: Training/Reward
    maxTrials: 30
    maxParallelTrials: 5
    params:
      - parameterName: critic_lr
        type: DOUBLE
        minValue: 0.0001
        maxValue: 0.001
      - parameterName: actor_lr
        type: DOUBLE
        minValue: 0.0001
        maxValue: 0.001
      - parameterName: gamma
        type: DOUBLE
        minValue: 0.9
        maxValue: 0.99
      - parameterName: tau
        type: DOUBLE
        minValue: 0.001
        maxValue: 0.01
      - parameterName: sigma
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.1
      - parameterName: sigma_tilda
        type: DOUBLE
        minValue: 0.01
        maxValue: 0.1
      - parameterName: c
        type: DOUBLE
        minValue: 0.05
        maxValue: 0.20
      - parameterName: grad_norm_clip
        type: DOUBLE
        minValue: 1.0
        maxValue: 100.0
      - parameterName: d
        type: INTEGER
        minValue: 2
        maxValue: 10
      - parameterName: batch_size
        type: DISCRETE
        discreteValues:
        - 32
        - 64
